name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # Ensure the master branch continues to build over time
    - cron: "0 12 */15 * *"

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
    # Checks-out the repository under $GITHUB_WORKSPACE, so the job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    # - name: Build with CMake
    #   run: |
    #     echo $(pwd)
    #     echo $GITHUB_WORKSPACE
    #     ls

    # Runs a set of commands using the runners shell
    - name: Build with Makefile
      run: |
        cd Builds/LinuxMakefile
        CXX=$(which clang++) CONFIG=Debug make -j VST
        CXX=$(which clang++) CONFIG=Release make -j VST
