name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # Ensure the master branch continues to build over time
    - cron: "0 12 */15 * *"

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
    # Checks-out the repository under $GITHUB_WORKSPACE, so the job can access it
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install juce-modules-source libfftw3-dev libxinerama-dev \
                         libwebkit2gtk-4.0-dev libcurl4-openssl-dev libflac-dev \
                         libvorbis-dev libogg-dev libjack-dev

    - name: Build with CMake, Clang
      run: |
        ls -l /usr/share/juce/modules/juce_audio_basics/buffers
        echo "========================================================"

        cd Builds/CLion
        cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=$(which clang) \
              -DCMAKE_CXX_COMPILER=$(which clang++) -S . -B build
        cmake --build build -j

    - name: Build with Makefile, GCC
      run: |
        cd Builds/LinuxMakefile
        CC=$(which gcc) CXX=$(which g++) CONFIG=Debug make -j
